name: 'Build & Test'

on:
  push:
    paths:
      - 'src/**'
  pull_request:
  workflow_dispatch:  

jobs:
  test:
    runs-on: 'ubuntu-22.04'
    steps:
      - name: checkout project
        uses: actions/checkout@v4
      - name: installing .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            7.0.x
            8.0.x
      - name: Build on Debug
        run: dotnet build -c Debug src/CuiLib.sln
      - name: Build on Release
        run: dotnet build -c Release src/CuiLib.sln
      - name: Run Tests
        run: dotnet test src/CuiLib.sln
